# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.provision "shell", path: "golang-install.sh"
  config.vm.provision "file", source: "../web-server.go", destination: "web-server.go"
end
